version: '3'
services:
  vprodb:
    image: chinmayapradhan/vprofiledb:${IMAGE_NAME}
    ports:
      - 3306:3306
    volumes:
      - vprodata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached:latest
    ports:
      - 11211:11211

  vpromq01:
    image: rabbitmq:latest
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest 
  vproapp:
    image: chinmayapradhan/vprofileapp:${IMAGE_NAME}
    ports:
      - 8080:8080
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps
  
  vproweb:
    image: chinmayapradhan/vprofileweb:${IMAGE_NAME}
    ports:
      - 80:80

volumes:
  vprodata: {}
  vproappdata: {}