apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
  rmq-pass: Z3Vlc3Q=  







# echo -n "vprodbpass" | base64
# echo -n "guest" | base64
# kubectl apply -f app-secret.yml
# kubectl get secret 
# kubectl describe secret 
